export PATH=$PATH:/bin
export PATH=$HOME/bin:$PATH
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export CC=/usr/bin/gcc

export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -t"
export VISUAL="emacsclient -c -a emacs"
export NVM_AUTO_USE=true
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH=$PATH:~/.local/bin
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/libpq/bin:$PATH"
export ZSH_DISABLE_COMPFIX="true"
export AUTOSUGGESTION_ACCEPT_RIGHT_ARROW=1
